### ISSUE TITLE
Is this repo unmaintained?

### ISSUE THREAD

**Issue by Billy-Sheppard** [CasperLabs/datasize-rs#11]
Hi, it appears this repo is a bit stagnant/unmaintained, is it possible for it to be addressed?

If so can it either be looked at by any of the current contributors @marc-casperlabs @mpapierski @fizyk20 @afck or handed over to someone new/forked?

Thanks :)

**Comment by marc-casperlabs** [comment]
It's not unmaintained, I recently published a release. I just missed the notifications about the PRs.

I'll look into this shortly, my sincerest apologies.

**Comment by Billy-Sheppard** [comment]
Amazing! Thanks Marc!
